// Generate the in-memory rule module consumed by the portable semantics
// engine. Runtime code never reads marionette.pl from a filesystem; this
// build-time copy keeps the .pl file authoritative and independently usable.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const sourcePath = join(root, 'spec', 'rules', 'marionette.pl');
const outputPath = join(root, 'src', 'rules-source.ts');
const source = readFileSync(sourcePath, 'utf8');
const output =
  '// Generated by scripts/embed-rules.mjs from spec/rules/marionette.pl.\n' +
  '// Do not edit this file directly; run `npm run generate:rules`.\n\n' +
  `export const MARIONETTE_RULES: string = ${JSON.stringify(source)};\n`;

if (process.argv.includes('--check')) {
  let current = null;
  try {
    current = readFileSync(outputPath, 'utf8');
  } catch {
    // The actionable stale-output message below covers a missing file too.
  }
  if (current !== output) {
    console.error('src/rules-source.ts is stale; run `npm run generate:rules` and commit it');
    process.exit(1);
  }
} else {
  writeFileSync(outputPath, output);
  console.log('generated src/rules-source.ts');
}
